// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/repository/repository.go -destination=internal/usecase/repository/mock/mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/code7unner/decentrathon5/terra-ledger/backend/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockParcelRepo is a mock of ParcelRepo interface.
type MockParcelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockParcelRepoMockRecorder
	isgomock struct{}
}

// MockParcelRepoMockRecorder is the mock recorder for MockParcelRepo.
type MockParcelRepoMockRecorder struct {
	mock *MockParcelRepo
}

// NewMockParcelRepo creates a new mock instance.
func NewMockParcelRepo(ctrl *gomock.Controller) *MockParcelRepo {
	mock := &MockParcelRepo{ctrl: ctrl}
	mock.recorder = &MockParcelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParcelRepo) EXPECT() *MockParcelRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockParcelRepo) Create(ctx context.Context, p *entity.Parcel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockParcelRepoMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockParcelRepo)(nil).Create), ctx, p)
}

// GetByCadastral mocks base method.
func (m *MockParcelRepo) GetByCadastral(ctx context.Context, cadastral string) (*entity.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCadastral", ctx, cadastral)
	ret0, _ := ret[0].(*entity.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCadastral indicates an expected call of GetByCadastral.
func (mr *MockParcelRepoMockRecorder) GetByCadastral(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCadastral", reflect.TypeOf((*MockParcelRepo)(nil).GetByCadastral), ctx, cadastral)
}

// ListNeedingSeasonalCheck mocks base method.
func (m *MockParcelRepo) ListNeedingSeasonalCheck(ctx context.Context, maxAge time.Duration) ([]entity.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNeedingSeasonalCheck", ctx, maxAge)
	ret0, _ := ret[0].([]entity.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNeedingSeasonalCheck indicates an expected call of ListNeedingSeasonalCheck.
func (mr *MockParcelRepoMockRecorder) ListNeedingSeasonalCheck(ctx, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNeedingSeasonalCheck", reflect.TypeOf((*MockParcelRepo)(nil).ListNeedingSeasonalCheck), ctx, maxAge)
}

// ListAll mocks base method.
func (m *MockParcelRepo) ListAll(ctx context.Context) ([]entity.Parcel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]entity.Parcel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockParcelRepoMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockParcelRepo)(nil).ListAll), ctx)
}

// UpdateOnChainAddress mocks base method.
func (m *MockParcelRepo) UpdateOnChainAddress(ctx context.Context, cadastral, addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnChainAddress", ctx, cadastral, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnChainAddress indicates an expected call of UpdateOnChainAddress.
func (mr *MockParcelRepoMockRecorder) UpdateOnChainAddress(ctx, cadastral, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnChainAddress", reflect.TypeOf((*MockParcelRepo)(nil).UpdateOnChainAddress), ctx, cadastral, addr)
}

// MockCertificateRepo is a mock of CertificateRepo interface.
type MockCertificateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCertificateRepoMockRecorder
	isgomock struct{}
}

// MockCertificateRepoMockRecorder is the mock recorder for MockCertificateRepo.
type MockCertificateRepoMockRecorder struct {
	mock *MockCertificateRepo
}

// NewMockCertificateRepo creates a new mock instance.
func NewMockCertificateRepo(ctrl *gomock.Controller) *MockCertificateRepo {
	mock := &MockCertificateRepo{ctrl: ctrl}
	mock.recorder = &MockCertificateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertificateRepo) EXPECT() *MockCertificateRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCertificateRepo) Create(ctx context.Context, cert *entity.NDVICertificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cert)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCertificateRepoMockRecorder) Create(ctx, cert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCertificateRepo)(nil).Create), ctx, cert)
}

// CreateBatch mocks base method.
func (m *MockCertificateRepo) CreateBatch(ctx context.Context, certs []entity.NDVICertificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, certs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockCertificateRepoMockRecorder) CreateBatch(ctx, certs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockCertificateRepo)(nil).CreateBatch), ctx, certs)
}

// ListByParcelInRange mocks base method.
func (m *MockCertificateRepo) ListByParcelInRange(ctx context.Context, cadastral string, from, to time.Time) ([]entity.NDVICertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParcelInRange", ctx, cadastral, from, to)
	ret0, _ := ret[0].([]entity.NDVICertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParcelInRange indicates an expected call of ListByParcelInRange.
func (mr *MockCertificateRepoMockRecorder) ListByParcelInRange(ctx, cadastral, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParcelInRange", reflect.TypeOf((*MockCertificateRepo)(nil).ListByParcelInRange), ctx, cadastral, from, to)
}

// GetLatest mocks base method.
func (m *MockCertificateRepo) GetLatest(ctx context.Context, cadastral string) (*entity.NDVICertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, cadastral)
	ret0, _ := ret[0].(*entity.NDVICertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockCertificateRepoMockRecorder) GetLatest(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockCertificateRepo)(nil).GetLatest), ctx, cadastral)
}

// ListByParcel mocks base method.
func (m *MockCertificateRepo) ListByParcel(ctx context.Context, cadastral string) ([]entity.NDVICertificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParcel", ctx, cadastral)
	ret0, _ := ret[0].([]entity.NDVICertificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParcel indicates an expected call of ListByParcel.
func (mr *MockCertificateRepoMockRecorder) ListByParcel(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParcel", reflect.TypeOf((*MockCertificateRepo)(nil).ListByParcel), ctx, cadastral)
}

// MockLienRepo is a mock of LienRepo interface.
type MockLienRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLienRepoMockRecorder
	isgomock struct{}
}

// MockLienRepoMockRecorder is the mock recorder for MockLienRepo.
type MockLienRepoMockRecorder struct {
	mock *MockLienRepo
}

// NewMockLienRepo creates a new mock instance.
func NewMockLienRepo(ctrl *gomock.Controller) *MockLienRepo {
	mock := &MockLienRepo{ctrl: ctrl}
	mock.recorder = &MockLienRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLienRepo) EXPECT() *MockLienRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLienRepo) Create(ctx context.Context, lien *entity.Encumbrance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lien)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLienRepoMockRecorder) Create(ctx, lien any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLienRepo)(nil).Create), ctx, lien)
}

// FindByWalletAndCadastral mocks base method.
func (m *MockLienRepo) FindByWalletAndCadastral(ctx context.Context, lenderWallet, cadastral string) (*entity.Encumbrance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByWalletAndCadastral", ctx, lenderWallet, cadastral)
	ret0, _ := ret[0].(*entity.Encumbrance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByWalletAndCadastral indicates an expected call of FindByWalletAndCadastral.
func (mr *MockLienRepoMockRecorder) FindByWalletAndCadastral(ctx, lenderWallet, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByWalletAndCadastral", reflect.TypeOf((*MockLienRepo)(nil).FindByWalletAndCadastral), ctx, lenderWallet, cadastral)
}

// GetByID mocks base method.
func (m *MockLienRepo) GetByID(ctx context.Context, id string) (*entity.Encumbrance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Encumbrance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLienRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLienRepo)(nil).GetByID), ctx, id)
}

// GetActive mocks base method.
func (m *MockLienRepo) GetActive(ctx context.Context, cadastral string) (*entity.Encumbrance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, cadastral)
	ret0, _ := ret[0].(*entity.Encumbrance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockLienRepoMockRecorder) GetActive(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockLienRepo)(nil).GetActive), ctx, cadastral)
}

// ListByParcel mocks base method.
func (m *MockLienRepo) ListByParcel(ctx context.Context, cadastral string) ([]entity.Encumbrance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParcel", ctx, cadastral)
	ret0, _ := ret[0].([]entity.Encumbrance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByParcel indicates an expected call of ListByParcel.
func (mr *MockLienRepoMockRecorder) ListByParcel(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParcel", reflect.TypeOf((*MockLienRepo)(nil).ListByParcel), ctx, cadastral)
}

// UpdateStatus mocks base method.
func (m *MockLienRepo) UpdateStatus(ctx context.Context, id string, status entity.LienStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockLienRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockLienRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockLenderRepo is a mock of LenderRepo interface.
type MockLenderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLenderRepoMockRecorder
	isgomock struct{}
}

// MockLenderRepoMockRecorder is the mock recorder for MockLenderRepo.
type MockLenderRepoMockRecorder struct {
	mock *MockLenderRepo
}

// NewMockLenderRepo creates a new mock instance.
func NewMockLenderRepo(ctrl *gomock.Controller) *MockLenderRepo {
	mock := &MockLenderRepo{ctrl: ctrl}
	mock.recorder = &MockLenderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLenderRepo) EXPECT() *MockLenderRepoMockRecorder {
	return m.recorder
}

// GetByAPIKey mocks base method.
func (m *MockLenderRepo) GetByAPIKey(ctx context.Context, key string) (*entity.Lender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAPIKey", ctx, key)
	ret0, _ := ret[0].(*entity.Lender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAPIKey indicates an expected call of GetByAPIKey.
func (mr *MockLenderRepoMockRecorder) GetByAPIKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAPIKey", reflect.TypeOf((*MockLenderRepo)(nil).GetByAPIKey), ctx, key)
}

// MockCreditScoreRepo is a mock of CreditScoreRepo interface.
type MockCreditScoreRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCreditScoreRepoMockRecorder
	isgomock struct{}
}

// MockCreditScoreRepoMockRecorder is the mock recorder for MockCreditScoreRepo.
type MockCreditScoreRepoMockRecorder struct {
	mock *MockCreditScoreRepo
}

// NewMockCreditScoreRepo creates a new mock instance.
func NewMockCreditScoreRepo(ctrl *gomock.Controller) *MockCreditScoreRepo {
	mock := &MockCreditScoreRepo{ctrl: ctrl}
	mock.recorder = &MockCreditScoreRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditScoreRepo) EXPECT() *MockCreditScoreRepoMockRecorder {
	return m.recorder
}

// GetByCadastral mocks base method.
func (m *MockCreditScoreRepo) GetByCadastral(ctx context.Context, cadastral string) (*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCadastral", ctx, cadastral)
	ret0, _ := ret[0].(*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCadastral indicates an expected call of GetByCadastral.
func (mr *MockCreditScoreRepoMockRecorder) GetByCadastral(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCadastral", reflect.TypeOf((*MockCreditScoreRepo)(nil).GetByCadastral), ctx, cadastral)
}

// Upsert mocks base method.
func (m *MockCreditScoreRepo) Upsert(ctx context.Context, score *entity.CreditScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockCreditScoreRepoMockRecorder) Upsert(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCreditScoreRepo)(nil).Upsert), ctx, score)
}

// MockSolanaClient is a mock of SolanaClient interface.
type MockSolanaClient struct {
	ctrl     *gomock.Controller
	recorder *MockSolanaClientMockRecorder
	isgomock struct{}
}

// MockSolanaClientMockRecorder is the mock recorder for MockSolanaClient.
type MockSolanaClientMockRecorder struct {
	mock *MockSolanaClient
}

// NewMockSolanaClient creates a new mock instance.
func NewMockSolanaClient(ctrl *gomock.Controller) *MockSolanaClient {
	mock := &MockSolanaClient{ctrl: ctrl}
	mock.recorder = &MockSolanaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolanaClient) EXPECT() *MockSolanaClientMockRecorder {
	return m.recorder
}

// GetAccountInfo mocks base method.
func (m *MockSolanaClient) GetAccountInfo(ctx context.Context, address string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountInfo", ctx, address)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountInfo indicates an expected call of GetAccountInfo.
func (mr *MockSolanaClientMockRecorder) GetAccountInfo(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountInfo", reflect.TypeOf((*MockSolanaClient)(nil).GetAccountInfo), ctx, address)
}

// GetRecentBlockhash mocks base method.
func (m *MockSolanaClient) GetRecentBlockhash(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentBlockhash", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentBlockhash indicates an expected call of GetRecentBlockhash.
func (mr *MockSolanaClientMockRecorder) GetRecentBlockhash(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentBlockhash", reflect.TypeOf((*MockSolanaClient)(nil).GetRecentBlockhash), ctx)
}

// GetSignaturesForAddress mocks base method.
func (m *MockSolanaClient) GetSignaturesForAddress(ctx context.Context, address string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignaturesForAddress", ctx, address, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignaturesForAddress indicates an expected call of GetSignaturesForAddress.
func (mr *MockSolanaClientMockRecorder) GetSignaturesForAddress(ctx, address, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignaturesForAddress", reflect.TypeOf((*MockSolanaClient)(nil).GetSignaturesForAddress), ctx, address, limit)
}

// SendTransaction mocks base method.
func (m *MockSolanaClient) SendTransaction(ctx context.Context, txBytes []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, txBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockSolanaClientMockRecorder) SendTransaction(ctx, txBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockSolanaClient)(nil).SendTransaction), ctx, txBytes)
}

// SimulateTransaction mocks base method.
func (m *MockSolanaClient) SimulateTransaction(ctx context.Context, txBytes []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateTransaction", ctx, txBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SimulateTransaction indicates an expected call of SimulateTransaction.
func (mr *MockSolanaClientMockRecorder) SimulateTransaction(ctx, txBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateTransaction", reflect.TypeOf((*MockSolanaClient)(nil).SimulateTransaction), ctx, txBytes)
}

// MockNDVIProvider is a mock of NDVIProvider interface.
type MockNDVIProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNDVIProviderMockRecorder
	isgomock struct{}
}

// MockNDVIProviderMockRecorder is the mock recorder for MockNDVIProvider.
type MockNDVIProviderMockRecorder struct {
	mock *MockNDVIProvider
}

// NewMockNDVIProvider creates a new mock instance.
func NewMockNDVIProvider(ctrl *gomock.Controller) *MockNDVIProvider {
	mock := &MockNDVIProvider{ctrl: ctrl}
	mock.recorder = &MockNDVIProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNDVIProvider) EXPECT() *MockNDVIProviderMockRecorder {
	return m.recorder
}

// FetchNDVI mocks base method.
func (m *MockNDVIProvider) FetchNDVI(ctx context.Context, cadastral string, lat, lon float64, startDate, endDate string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNDVI", ctx, cadastral, lat, lon, startDate, endDate)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNDVI indicates an expected call of FetchNDVI.
func (mr *MockNDVIProviderMockRecorder) FetchNDVI(ctx, cadastral, lat, lon, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNDVI", reflect.TypeOf((*MockNDVIProvider)(nil).FetchNDVI), ctx, cadastral, lat, lon, startDate, endDate)
}

// MockSatelliteProvider is a mock of SatelliteProvider interface.
type MockSatelliteProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSatelliteProviderMockRecorder
	isgomock struct{}
}

// MockSatelliteProviderMockRecorder is the mock recorder for MockSatelliteProvider.
type MockSatelliteProviderMockRecorder struct {
	mock *MockSatelliteProvider
}

// NewMockSatelliteProvider creates a new mock instance.
func NewMockSatelliteProvider(ctrl *gomock.Controller) *MockSatelliteProvider {
	mock := &MockSatelliteProvider{ctrl: ctrl}
	mock.recorder = &MockSatelliteProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSatelliteProvider) EXPECT() *MockSatelliteProviderMockRecorder {
	return m.recorder
}

// FetchNDVI mocks base method.
func (m *MockSatelliteProvider) FetchNDVI(ctx context.Context, cadastral string, lat, lon float64, startDate, endDate string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNDVI", ctx, cadastral, lat, lon, startDate, endDate)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNDVI indicates an expected call of FetchNDVI.
func (mr *MockSatelliteProviderMockRecorder) FetchNDVI(ctx, cadastral, lat, lon, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNDVI", reflect.TypeOf((*MockSatelliteProvider)(nil).FetchNDVI), ctx, cadastral, lat, lon, startDate, endDate)
}

// FetchTimeSeries mocks base method.
func (m *MockSatelliteProvider) FetchTimeSeries(ctx context.Context, cadastral string, lat, lon float64, startDate, endDate string) (*entity.SatelliteTimeSeries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTimeSeries", ctx, cadastral, lat, lon, startDate, endDate)
	ret0, _ := ret[0].(*entity.SatelliteTimeSeries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTimeSeries indicates an expected call of FetchTimeSeries.
func (mr *MockSatelliteProviderMockRecorder) FetchTimeSeries(ctx, cadastral, lat, lon, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTimeSeries", reflect.TypeOf((*MockSatelliteProvider)(nil).FetchTimeSeries), ctx, cadastral, lat, lon, startDate, endDate)
}

// MockEGISSOracle is a mock of EGISSOracle interface.
type MockEGISSOracle struct {
	ctrl     *gomock.Controller
	recorder *MockEGISSOracleMockRecorder
	isgomock struct{}
}

// MockEGISSOracleMockRecorder is the mock recorder for MockEGISSOracle.
type MockEGISSOracleMockRecorder struct {
	mock *MockEGISSOracle
}

// NewMockEGISSOracle creates a new mock instance.
func NewMockEGISSOracle(ctrl *gomock.Controller) *MockEGISSOracle {
	mock := &MockEGISSOracle{ctrl: ctrl}
	mock.recorder = &MockEGISSOracleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEGISSOracle) EXPECT() *MockEGISSOracleMockRecorder {
	return m.recorder
}

// GetParcelSnapshot mocks base method.
func (m *MockEGISSOracle) GetParcelSnapshot(ctx context.Context, cadastral string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParcelSnapshot", ctx, cadastral)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParcelSnapshot indicates an expected call of GetParcelSnapshot.
func (mr *MockEGISSOracleMockRecorder) GetParcelSnapshot(ctx, cadastral any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParcelSnapshot", reflect.TypeOf((*MockEGISSOracle)(nil).GetParcelSnapshot), ctx, cadastral)
}

// MockCreditScorer is a mock of CreditScorer interface.
type MockCreditScorer struct {
	ctrl     *gomock.Controller
	recorder *MockCreditScorerMockRecorder
	isgomock struct{}
}

// MockCreditScorerMockRecorder is the mock recorder for MockCreditScorer.
type MockCreditScorerMockRecorder struct {
	mock *MockCreditScorer
}

// NewMockCreditScorer creates a new mock instance.
func NewMockCreditScorer(ctrl *gomock.Controller) *MockCreditScorer {
	mock := &MockCreditScorer{ctrl: ctrl}
	mock.recorder = &MockCreditScorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditScorer) EXPECT() *MockCreditScorerMockRecorder {
	return m.recorder
}

// ComputeScore mocks base method.
func (m *MockCreditScorer) ComputeScore(ctx context.Context, input *entity.ScoringInput) (*entity.CreditScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeScore", ctx, input)
	ret0, _ := ret[0].(*entity.CreditScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeScore indicates an expected call of ComputeScore.
func (mr *MockCreditScorerMockRecorder) ComputeScore(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeScore", reflect.TypeOf((*MockCreditScorer)(nil).ComputeScore), ctx, input)
}

// MockConsentRepo is a mock of ConsentRepo interface.
type MockConsentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConsentRepoMockRecorder
	isgomock struct{}
}

// MockConsentRepoMockRecorder is the mock recorder for MockConsentRepo.
type MockConsentRepoMockRecorder struct {
	mock *MockConsentRepo
}

// NewMockConsentRepo creates a new mock instance.
func NewMockConsentRepo(ctrl *gomock.Controller) *MockConsentRepo {
	mock := &MockConsentRepo{ctrl: ctrl}
	mock.recorder = &MockConsentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentRepo) EXPECT() *MockConsentRepoMockRecorder {
	return m.recorder
}

// GetByWallet mocks base method.
func (m *MockConsentRepo) GetByWallet(ctx context.Context, walletAddress string) (*entity.Consent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWallet", ctx, walletAddress)
	ret0, _ := ret[0].(*entity.Consent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWallet indicates an expected call of GetByWallet.
func (mr *MockConsentRepoMockRecorder) GetByWallet(ctx, walletAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWallet", reflect.TypeOf((*MockConsentRepo)(nil).GetByWallet), ctx, walletAddress)
}

// Grant mocks base method.
func (m *MockConsentRepo) Grant(ctx context.Context, walletAddress string) (*entity.Consent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grant", ctx, walletAddress)
	ret0, _ := ret[0].(*entity.Consent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grant indicates an expected call of Grant.
func (mr *MockConsentRepoMockRecorder) Grant(ctx, walletAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MockConsentRepo)(nil).Grant), ctx, walletAddress)
}

// ListAccessLog mocks base method.
func (m *MockConsentRepo) ListAccessLog(ctx context.Context, walletAddress string) ([]entity.ConsentLogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessLog", ctx, walletAddress)
	ret0, _ := ret[0].([]entity.ConsentLogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessLog indicates an expected call of ListAccessLog.
func (mr *MockConsentRepoMockRecorder) ListAccessLog(ctx, walletAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessLog", reflect.TypeOf((*MockConsentRepo)(nil).ListAccessLog), ctx, walletAddress)
}

// LogAccess mocks base method.
func (m *MockConsentRepo) LogAccess(ctx context.Context, entry *entity.ConsentLogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAccess", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAccess indicates an expected call of LogAccess.
func (mr *MockConsentRepoMockRecorder) LogAccess(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAccess", reflect.TypeOf((*MockConsentRepo)(nil).LogAccess), ctx, entry)
}

// Revoke mocks base method.
func (m *MockConsentRepo) Revoke(ctx context.Context, walletAddress string) (*entity.Consent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, walletAddress)
	ret0, _ := ret[0].(*entity.Consent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockConsentRepoMockRecorder) Revoke(ctx, walletAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockConsentRepo)(nil).Revoke), ctx, walletAddress)
}
